fix: Correct the CORS handler logic
edgexfoundry/go-mod-bootstrap pull request #290
Opened 2021-10-29 16:34 UTC by cloudxxx8

Modify CORS process middleware and implement preflight handling to meet:
https://www.html5rocks.com/en/tutorials/cors//#toc-cors-server-flowchart

Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)  issue https://github.com/edgexfoundry/edgex-docs/issues/608 opened
  <link to docs PR>

## Testing Instructions

Test normal request:
1. Set configuration `EnableCORS = true`, and start an EdgeX service
2. Send a http request with a header `Origin`
3. Very the response header contains `Access-Control-Expose-Headers`, `Access-Control-Allow-Origin`, `Access-Control-Allow-Credentials` with the values the same as the `Service.CORSConfiguration` configuration (if `CORSAllowCredentials = false`, there is no `Access-Control-Allow-Credentials` header), and `Vary: Origin`

Test preflight request:
1. Set configuration `EnableCORS = true` and start an EdgeX service
2. Send an `OPTIONS` http request with a valid header "Access-Control-Request-Method" value, such as `GET`,  and `Origin`
3. Very the response status code is 200 with the header value `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`, `Access-Control-Allow-Origin`, `Access-Control-Allow-Credentials`, and `Access-Control-Max-Age` the same as the `Service.CORSConfiguration` configuration (if `CORSAllowCredentials = false`, there is no `Access-Control-Allow-Credentials` header), and `Vary: Origin`

2021-10-29 18:14 UTC, bnevis-i requested changes

2021-10-29 18:14 UTC, bnevis-i commented on bootstrap/handlers/cors.go
> +	AccessControlRequestMethods = "Access-Control-Request-Methods"
Severe bug:

```suggestion
	AccessControlRequestMethod = "Access-Control-Request-Method"
```

2021-10-29 18:28 UTC, bnevis-i commented
Other than the one goof on the header, this looks ready to merge.

2021-10-31 07:48 UTC, cloudxxx8 commented on bootstrap/handlers/cors.go
> +	AccessControlRequestMethods = "Access-Control-Request-Methods"
thanks, nice catch
modified

2021-10-31 07:48 UTC, cloudxxx8 commented
Added Vary header

2021-10-31 10:20 UTC, cloudxxx8 commented
added unit tests

2021-10-31 16:10 UTC, bnevis-i approved these changes

2021-11-01 14:20 UTC, lenny-intel approved these changes
LGTM

2021-11-01 14:20 UTC, merged