Messaging client
edgexfoundry/go-mod-bootstrap pull request #384
Opened 2022-10-19 21:35 UTC by lenny-intel

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [x] I have opened a PR for the related docs change (if not, why?)
  TBD

## Testing Instructions
TBD

## New Dependency Instructions (If applicable)

2022-10-19 21:40 UTC, lenny-intel commented
@cloudxxx8 , If you merge, please `Sqaush and Merge` and remove the first commit message. Not sure how that got there, but the list of changed files is correct. THX!

2022-10-20 03:44 UTC, hahattan requested changes

2022-10-20 15:02 UTC, lenny-intel commented on bootstrap/handlers/clients.go
> +					lc.Errorf("Unable to create Command client using MessageBus: %s", "MessageBus Client was not created")
I did this on purpose so tests can verify Errorf called.

2022-10-20 15:02 UTC, lenny-intel commented on bootstrap/handlers/clients.go
> +				client, _ = clientsMessaging.NewCommandClient(messageClient, serviceInfo.Topics, timeout)
Yep, missed that. THX! Will add err check.

2022-10-20 18:00 UTC, lenny-intel commented on bootstrap/handlers/clients.go
> +				client, _ = clientsMessaging.NewCommandClient(messageClient, serviceInfo.Topics, timeout)
Fixed

2022-10-21 02:34 UTC, hahattan approved these changes
LGTM

2022-10-21 04:20 UTC, lenny-intel commented
@cloudxxx8 , need your approval as committer

2022-10-21 15:49 UTC, jim-wang-intel approved these changes

2022-10-21 18:15 UTC, merged