feat: Add command line/environment flag for commonConfig
edgexfoundry/go-mod-bootstrap pull request #487
Opened 2023-03-20 21:04 UTC by ejlee3

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

**Non-secure mode testing **
1. set the environment variable for non-secure testing `export EDGEX_SECURITY_SECRET_STORE=false`
2. run the latest compose builder `make run no-secty` to start core services
3. stop core data
4. remove the core data configuration in consul
5. modify local go-mod in edgex-go to use bootstrap from [this branch](https://github.com/ejlee3/go-mod-bootstrap/tree/common-config-flag)
7. build core data `make data`
9. run core-data locally and ensure that the configuration loads `cd cmd/core-data` and `./core-data -cc ../core-common-config-bootstrapper/res/configuration.yaml`
10. Verify that the core data configuration and common config were loaded using curl `curl http://localhost:59880/api/v2/config | json_pp`

**secure mode testing **
Repeat the above steps with `EDGEX_SECRUITY_SECRETS_STORE=true`, run all services in secure mode, and run core data with `sudo` 

## New Dependency Instructions (If applicable)

2023-03-20 21:48 UTC, lenny-intel requested changes

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/config/config.go
>  	if !useProvider || !cp.providerHasConfig || cp.overwriteConfig {
```suggestion
	if !useProvider {
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/config/config.go
> +			err := cp.loadCommonConfigFromUri(commonConfigLocation, serviceConfig, serviceType)
Lets not use UIR term yet. When we do implement URI if will be a generic function not specific to configuration. My thought is this loadCommonConfigFromFile will can it to do the actually loading once we have it in place.
```suggestion
			err := cp.loadCommonConfigFromFile(commonConfigLocation, serviceConfig, serviceType)
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/config/config.go
> +				return fmt.Errorf("could not load oommon config: %s", err.Error())
error already has context
```suggestion
				return err
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/config/config.go
> +	//TODO: implement reading from URI
The TODO can be removed

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/config/config.go
> +		return fmt.Errorf("could not find all-services section in config %s", configFile)
```suggestion
		return fmt.Errorf("could not find all-services section in common config %s", configFile)
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/config/config.go
> +			return fmt.Errorf("could not find %s section in config %s", appServicesKey, configFile)
```suggestion
			return fmt.Errorf("could not find %s section in common config %s", appServicesKey, configFile)
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/config/config.go
> +			return fmt.Errorf("could not find %s section in config %s", deviceServicesKey, configFile)
```suggestion
			return fmt.Errorf("could not find %s section in common config %s", deviceServicesKey, configFile)
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/config/config.go
> +		return fmt.Errorf("could not load common configuration %s: %s", configFile, err.Error())
error already has context
```suggestion
		return err
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/config/config_test.go
> +				assert.NotEmpty(t, tc.serviceType)
Why is this assert needed? It is part of the tests code, not the code being tested.

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/environment/variables.go
> +func GetCommonConfig(lc logger.LoggingClient, commonConfig string) string {
```suggestion
func GetCommonConfigFileName(lc logger.LoggingClient, commonConfigFileName string) string {
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/environment/variables_test.go
> +func TestGetCommonConfig(t *testing.T) {
```suggestion
func TestGetCommonConfigFileName(t *testing.T) {
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/flags/flags.go
> +// CommonConfig returns the uri for the common configuration
```suggestion
// CommonConfig returns the location for the common configuration
```

2023-03-20 21:48 UTC, lenny-intel commented on bootstrap/flags/flags.go
> +			"    -cc, --commonConfig             Takes the URI that specifies where the common configuration is pulled from when\n"+
```suggestion
			"    -cc, --commonConfig             Takes the location that specifies where the common configuration is loaded from when\n"+
```

2023-03-20 22:58 UTC, lenny-intel requested changes

2023-03-20 22:58 UTC, lenny-intel commented on bootstrap/flags/flags.go
> +			"    -cc, --commonConfig             Takes the location to specifies where the common configuration is loaded from when\n"+
Takes the location to where the common configuration is loaded ....

2023-03-20 22:58 UTC, lenny-intel commented on bootstrap/config/config.go
> +		}
```suggestion
	} else {
		// Now must load configuration from local file if any of these conditions are true
		commonConfigLocation := environment.GetCommonConfigFileName(cp.lc, cp.flags.CommonConfig())
		if commonConfigLocation != "" {
			err := cp.loadCommonConfigFromFile(commonConfigLocation, serviceConfig, serviceType)
			if err != nil {
				return err
			}
		}
	}
	
       	// Now must load private configuration from local file if any of these conditions are true
       if !useProvider || !cp.providerHasConfig || cp.overwriteConfig {```

2023-03-20 23:29 UTC, lenny-intel approved these changes
LGTM.

2023-03-20 23:29 UTC, lenny-intel commented on bootstrap/config/config.go
> +		if !useProvider || !cp.providerHasConfig || cp.overwriteConfig {
Move outside the else cause

2023-03-21 09:47 UTC, MonicaisHer commented
I updated the go-mod in edgex-go to use the bootstrap from this PR, but encountered some errors while building edgex-go. Here are the build steps and error details:

1. I added `replace github.com/edgexfoundry/go-mod-bootstrap/v3 v3.0.0-dev.54 => github.com/ejlee3/go-mod-bootstrap/v3 v3.0.0-20230320232408-c3ed78377b49` to the go.mod file and ran `go mod tidy`
2. I ran `snapcraft` to build the snapped binary
However, I received the following error:
```
internal/security/config/command/flags_common.go:37:9: cannot use &commonFlags (value of type *commonFlags) as flags.Common value in return statement: *commonFlags does not implement flags.Common (missing method CommonConfig)
make: *** [Makefile:134: cmd/secrets-config/secrets-config] Error 1
```
I'm wondering if there are any adjustments that need to be made to the edgex-go code as well?

2023-03-21 11:18 UTC, cloudxxx8 commented on bootstrap/config/config.go
> +	allServicesConfig, ok := commonConfig["all-services"].(map[string]any)
use `allServicesKey`

2023-03-21 11:18 UTC, cloudxxx8 commented on bootstrap/config/config.go
> +func (cp *Processor) loadConfigYamlFromFile(yamlFile string) (map[string]interface{}, error) {
use `map[string]any` instead of `map[string]interface{}`

2023-03-21 11:18 UTC, cloudxxx8 commented on bootstrap/config/config.go
> +	data := make(map[string]interface{})
use `map[string]any` instead of `map[string]interface{}`

2023-03-21 15:59 UTC, lenny-intel commented
> I updated the go-mod in edgex-go to use the bootstrap from this PR, but encountered some errors while building edgex-go. Here are the build steps and error details:
> 
> 1. added `replace github.com/edgexfoundry/go-mod-bootstrap/v3 v3.0.0-dev.54 => github.com/ejlee3/go-mod-bootstrap/v3 v3.0.0-20230320232408-c3ed78377b49` to the go.mod file and ran `go mod tidy`
> 2. ran `snapcraft` to build the snapped binary
> 
> However, I received the following error:
> 
> ```
> internal/security/config/command/flags_common.go:37:9: cannot use &commonFlags (value of type *commonFlags) as flags.Common value in return statement: *commonFlags does not implement flags.Common (missing method CommonConfig)
> make: *** [Makefile:134: cmd/secrets-config/secrets-config] Error 1
> ```
> 
> I'm wondering if there are any adjustments that need to be made to the edgex-go code as well?

@MonicaisHer Yes, edgex-go will need tweaks for those services that re-implement the flags.Common interface. They need to implement the CommonConfig API.

2023-03-21 17:58 UTC, lenny-intel approved these changes
LGTM

2023-03-21 19:21 UTC, ejlee3 commented
> > I updated the go-mod in edgex-go to use the bootstrap from this PR, but encountered some errors while building edgex-go. Here are the build steps and error details:
> > 
> > 1. added `replace github.com/edgexfoundry/go-mod-bootstrap/v3 v3.0.0-dev.54 => github.com/ejlee3/go-mod-bootstrap/v3 v3.0.0-20230320232408-c3ed78377b49` to the go.mod file and ran `go mod tidy`
> > 2. ran `snapcraft` to build the snapped binary
> > 
> > However, I received the following error:
> > ```
> > internal/security/config/command/flags_common.go:37:9: cannot use &commonFlags (value of type *commonFlags) as flags.Common value in return statement: *commonFlags does not implement flags.Common (missing method CommonConfig)
> > make: *** [Makefile:134: cmd/secrets-config/secrets-config] Error 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm wondering if there are any adjustments that need to be made to the edgex-go code as well?
> 
> @MonicaisHer Yes, edgex-go will need tweaks for those services that re-implement the flags.Common interface. They need to implement the CommonConfig API.

Draft PR for edgex-go changes is here: https://github.com/edgexfoundry/edgex-go/pull/4464

2023-03-21 20:49 UTC, lenny-intel commented
@MonicaisHer , please let us know once you have verified in edgex-go snap so we can merge this PR. THX!

2023-03-22 00:51 UTC, cloudxxx8 approved these changes
LGTM

2023-03-22 10:19 UTC, MonicaisHer approved these changes
Thank you! I tested this [PR](https://github.com/edgexfoundry/edgex-go/pull/4464) with snap to use a common config option, and it worked as expected. I was able to choose not to use the config provider and instead pull the common config from a file. The environment overrides were then applied after that. Here are the steps I used:
```
# Install snap built from this PR's changes
$ snap install --dangerous ./edgexfoundry_3.0.0-dev.108_amd64.snap

# Set not to use config provider
sudo snap set edgexfoundry apps.core-data.config.edgex-config-provider='none'

# Pull common config
sudo snap set edgexfoundry apps.core-data.config.edgex-common-config=./config/core-common-config-bootstrapper/res/configuration.yaml

# Set test environment variables
sudo snap set edgexfoundry apps.core-data.config.service-startupmsg='manual-snap-testing'

snap restart edgexfoundry.core-data
```
To verify that the common config was pulled and the environment variables were applied:
```
$ journalctl -f | grep core-data
app=core-data source=variables.go:402 msg="Variables override of 'Configuration Provider Information' by environment variable: EDGEX_CONFIG_PROVIDER=none"
app=core-data source=variables.go:402 msg="Variables override of '-cc/--commonConfig' by environment variable: EDGEX_COMMON_CONFIG=./config/core-common-config-bootstrapper/res/configuration.yaml
app=core-data source=config.go:599 msg="reading ./config/core-common-config-bootstrapper/res/configuration.yaml"
app=core-data source=config.go:194 msg="Common configuration loaded from file with 1 overrides applied"
app=core-data source=message.go:51 msg="Starting core-data 3.0.0-dev.108 "
app=core-data source=message.go:55 msg="manual-snap-testing"
```

2023-03-22 15:47 UTC, merged