feat: support /api/v3/secret endpoint in non-secure mode
edgexfoundry/go-mod-bootstrap pull request #542
Opened 2023-05-12 22:28 UTC by ajcasagrande

Implements the StoreSecret function for InsecureProvider. If the ConfigurationClient is in use, it will be used to store the secret, otherwise an error is returned.

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [X] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

**Run the new unit tests**
```
make test
```

**Try it out yourself**
1. clone latest edgex-compose
2. modify a device service to build using this code
go.mod:
```
replace github.com/edgexfoundry/go-mod-bootstrap/v3 => ../go-mod-bootstrap
```
3. build docker image
```
make docker
```
4. tag image so it is latest:
```
 docker tag edgexfoundry/device-usb-camera:0.0.0-dev nexus3.edgexfoundry.org:10004/device-usb-camera:latest 
```
5. pull latest edgex images
```
cd compose-builder
make pull
```
6. deploy in non-secure mode with `device-usb-camera`
```
make run no-secty ds-usb-camera
```
7. Wait for the service to start up
8. post a secret to to said device service:
```sh
curl --data '{
    "apiVersion":"v3",
    "secretName": "rtspauth",
    "secretData":[
        {
            "key":"username",
            "value":"<pick-a-username>"
        },
        {
            "key":"password",
            "value":"<pick-a-secure-password>"
        }
    ]
}' -X POST http://localhost:59989/api/v3/secret
```
9. expect a 201 Created
```
{"apiVersion":"v3","statusCode":201}
```
10. Verify the data is successfully in consul
http://localhost:8500/ui/dc1/kv/edgex/v3/device-usb-camera/Writable/InsecureSecrets

## New Dependency Instructions (If applicable)

2023-05-12 23:50 UTC, ajcasagrande commented
recheck

2023-05-15 15:51 UTC, lenny-intel requested changes

2023-05-15 15:51 UTC, lenny-intel commented on bootstrap/secret/insecure.go
> +	writableKey        = "Writable"
Make the one here public and use it. 
https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/bootstrap/config/config.go#L52

2023-05-15 15:51 UTC, lenny-intel commented on bootstrap/secret/insecure.go
> +		err = configClient.PutConfigurationValue(fmt.Sprintf("%s/SecretData/%s", basePath, key), []byte(value))
`SecretData` should be a constant also since it is also used in the unit tests.

2023-05-15 15:52 UTC, lenny-intel commented on bootstrap/secret/insecure.go
> +	writableKey        = "Writable"
ok with the other InsecureSecrets specific constants being here.

2023-05-17 15:28 UTC, lenny-intel approved these changes
LGTM and TSC approved

2023-05-17 15:29 UTC, merged