CommandClient can encode MessageBus topic
edgexfoundry/go-mod-bootstrap pull request #716
Opened 2024-06-17 12:33 UTC by weichou1229

Add enableNameFieldEscape parameter to CommandClient to enable MessageBus topic path encoding

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **not impact**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **not impact**
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2024-06-17 12:39 UTC, weichou1229 commented
This PR is based on the https://github.com/edgexfoundry/go-mod-messaging/pull/331.

2024-06-21 09:52 UTC, cloudxxx8 requested changes

2024-06-21 09:52 UTC, cloudxxx8 commented on go.mod
> +	github.com/edgexfoundry/go-mod-core-contracts/v3 v3.2.0-dev.23
```suggestion
	github.com/edgexfoundry/go-mod-core-contracts/v3 v3.2.0-dev.24
```

2024-06-21 09:57 UTC, weichou1229 commented on go.mod
> +	github.com/edgexfoundry/go-mod-core-contracts/v3 v3.2.0-dev.23
Updated.

2024-06-21 10:12 UTC, cloudxxx8 approved these changes
LGTM

2024-06-21 10:12 UTC, merged