feat: use zero trust dialer again
edgexfoundry/go-mod-bootstrap pull request #735
Opened 2024-07-22 12:14 UTC by dovholuknf

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2024-07-22 12:21 UTC, cloudxxx8 requested changes

2024-07-22 12:21 UTC, cloudxxx8 commented on bootstrap/registration/registry.go
> +		// secretProvider.SetHttpTransport(http.DefaultTransport)
```
if (bootstrapConfig.Registry.Type == "keeper") {
  secretProvider.SetHttpTransport(http.DefaultTransport)
}
```

2024-07-22 12:25 UTC, cloudxxx8 approved these changes
LGTM

2024-07-22 12:25 UTC, dovholuknf commented on bootstrap/registration/registry.go
> +		// secretProvider.SetHttpTransport(http.DefaultTransport)
updated

2024-07-22 20:40 UTC, dovholuknf commented
@cloudxxx8 -- i removed a second location where the bypass was put in place. i didn't see and equivalent of:

> bootstrapConfig.Registry.Type == "keeper"

so i removed it. Maybe I missed it?

2024-07-24 02:53 UTC, cloudxxx8 commented
close this PR due to the byPass code is removed from https://github.com/edgexfoundry/go-mod-bootstrap/pull/736

2024-07-24 02:53 UTC, closed without merging