feat: Enhance the auth hook func to support external JWT
edgexfoundry/go-mod-bootstrap pull request #811
Opened 2024-12-26 01:55 UTC by lindseysimple

Resolves #810. Enhance the auth middleware func to support external JWT verifcation.

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2025-01-06 13:06 UTC, cloudxxx8 requested changes

2025-01-06 13:06 UTC, cloudxxx8 commented on bootstrap/handlers/headers/key_test.go
> +// Copyright (C) 2024 IOTech Ltd
```suggestion
// Copyright (C) 2025 IOTech Ltd
```
update all the copyright to 2025

2025-01-07 01:58 UTC, lindseysimple commented on bootstrap/handlers/auth_middleware.go
> +const openBaoIssuer = "/v1/identity/oidc"
Done

2025-01-07 01:58 UTC, lindseysimple commented on bootstrap/handlers/auth_middleware.go
> +func SecretStoreAuthenticationHandlerFunc(secretProvider interfaces.SecretProviderExt, lc logger.LoggingClient, token string, c echo.Context) error {
Done

2025-01-07 01:58 UTC, lindseysimple commented on bootstrap/handlers/headers/key_test.go
> +// Copyright (C) 2024 IOTech Ltd
Done

2025-01-07 02:47 UTC, cloudxxx8 approved these changes
LGTM

2025-01-07 02:47 UTC, merged